DROP TABLE IF NOT EXISTS users;
CREATE TABLE users (
	id UNSIGNED SMALLINT primary key AUTO_INCREMENT,
	INDEX username VARCHAR(50) NOT NULL,
	password VARCHAR(41) NOT NULL,
	firstName VARCHAR(50),
	lastName VARCHAR(50),
	INDEX email VARCHAR(75) NOT NULL,
	enabled boolean NOT NULL default true) ENGINE=INNODB;

CREATE TABLE groups (
	id UNSIGNED SMALLINT primary key AUTO_INCREMENT,
	INDEX groupname VARCHAR(50) NOT NULL,
	owner UNSIGNED SMALLINT REFERENCES users(id),
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	members TEXT NOT NULL,
	admins TEXT NOT NULL,
	enabled boolean default true) ENGINE=INNODB;

CREATE TABLE chats (
	id UNSIGNED INT primary key AUTO_INCREMENT,
	name VARCHAR(20) not null,
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	atime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	mtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	INDEX UID INT REFERENCES users(id) NOT NULL,
	INDEX GID INT REFERENCES groups(id) NOT NULL,
	INDEX OwnerPermission TINYINT NOT NULL,
	INDEX GroupPermission TINYINT NOT NULL,
	INDEX OtherPermission TINYINT NOT NULL,
	files TEXT) ENGINE=INNODB;
	
CREATE TABLE chatEntries (
	id UNSIGNED INT primary key AUTO_INCREMENT,
	author UNSIGNED SMALLINT INT REFERENCES users(id),
	INDEX chatID INT REFERENCES chats(id),
	ctime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	type ENUM('txt', 'file') DEFAULT 'txt',
	content TEXT NOT NULL) ENGINE=INNODB;

CREATE TABLE files (
	id UNSIGNED INT primary key AUTO_INCREMENT,
	author UNSIGNED SMALLINT INT REFERENCES users(id) NOT NULL,
	owner UNSIGNED SMALLINT INT REFERENCES users(id) NOT NULL,
	INDEX chatID INT REFERENCES chats(id) NOT NULL,
	url varchar(50) NOT NULL) ENGINE=INNODB;
	